spring:
  datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/person-api?useTimezone=true&serverTimezone=UTC
      username: postgres
      password: banco321
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
